# Generated by Django 3.1.1 on 2020-09-04 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('person', models.CharField(max_length=100, verbose_name='Pessoa')),
                ('subject', models.CharField(max_length=100, verbose_name='Assunto')),
                ('priority', models.CharField(choices=[('alta', 'ALTA'), ('media', 'MEDIA'), ('baixa', 'BAIXA')], max_length=5, verbose_name='Prioridade')),
                ('place', models.CharField(max_length=100, verbose_name='Local')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('contact', models.CharField(max_length=20, verbose_name='Telefone')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['date'], name='agendas_age_date_3321f5_idx'),
        ),
    ]
