# Generated by Django 3.1.1 on 2020-09-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('person', models.CharField(max_length=100, verbose_name='Pessoa')),
                ('subject', models.CharField(max_length=100, verbose_name='Assunto')),
                ('priority', models.CharField(choices=[('alta', 'ALTA'), ('media', 'MEDIA'), ('baixa', 'BAIXA')], max_length=5, verbose_name='Prioridade')),
                ('place', models.CharField(max_length=100, verbose_name='Local')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('contact', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
        ),
    ]
