# Generated by Django 3.1.1 on 2020-09-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_auto_20200902_0713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['-date']},
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['date'], name='agendas_age_date_3321f5_idx'),
        ),
    ]
